config/routes.rb
Rails.application.routes.draw do
  

  root :to => "visitors#index"
  get "signout", to: "visitors#signout"

  resources :products
  devise_for :users
  resources :attendance
  resources :messages
  resources :payslips
  resources :cab_services
  resources :administration

  resources :bank_account do
    collection do
      get 'index'
      post 'create'
      post 'new'
      get 'new'
      get 'account'
      
    end
  end

  resources :leave_management do
    collection do
      get 'index'
      post 'index'
      post 'create'
      post 'new'
      get 'new'
      get 'approve_leave'
      get 'reject_leave'
      
    end
  end

  resources :users do
    collection do
      get 'index'
      post 'create'
      post 'new'
      get 'new'
      
    end
  end

  resources :admin do
    collection do
      get 'index'
      get 'download_employees'
      get 'employee_bank_details'
      get 'account'
      get 'profile_delete'
      get 'leave_application'
      post 'profile_delete'
      get 'profile_edit'
      get 'update_profile'
      post 'update_profile'
      post 'profile_edit'
      get 'destroy'
      get 'credentials'
      get 'download_bank_accounts'
      get 'approve_leave'
      get 'reject_leave'
    
    end
  end

  resources :profile do
    collection do
      get 'index'
      post 'index'
      post 'create'
      get 'destroy'
      get 'update'
      post 'update'
      
    end
  end

  resources :administration do
    collection do
      get 'index'
      post 'index'
      post 'create'
      get 'account'
      get 'destroy'
      get 'update'
      post 'update'
    end
  end    


end  

app/views/admin/employee_bank_details.html.erb
<div class="main">
  <div class="wide_cont custom-background" style="background:transparent;">
    <div class="doc-main">
      <div class="doc-content">
        <div class="" style ="text-align: center;" ><h2>BANK DETAILS</h2>
        <div class="rgt" style ="float:right ;" >
          <button class="btn btn-primary" style="margin-bottom: 14px;">
            Total Accounts:
              <%= @bank_details_count %>
          </button>
          <%=  link_to("Download Bank Accounts ",download_bank_accounts_admin_index_path(format: "csv"), :class => 'btn btn-primary', :style => "margin-bottom: 14px;") %>
        </div>
        
        <table class="responstable">
          <thead>
            <tr>
              <td>
                <b>
                  #
                </b>
              </td>
              <td>
                <b>
                  Employee ID
                </b>
              </td>
              <td>
                <b>
                  Full Name
                </b>
              </td>
              <td>
                <b>
                  Bank Name
                </b>
              </td>
              <td>
                <b>
                  Account Number
                </b>
              </td>
              <td>
                <b>
                  Bank Branch
                </b>
              </td>
              <td>
                <b>
                  IFSC Code
                </b>
              </td>
              <td>
                <b>
                  Status
                </b>
              </td>
              <td>
                <b>
                  CREATED AT
                </b>
              </td>
            </tr>
            <% @bank_details.each_with_index do |bank, index| %>
              <% profile = bank.profile %>
              <tr>
                <td>
                  <%= index %>
                </td>
                <td>
                  <%= profile.employee_number if profile.present? %>
                </td>
                
                <td>
                  <%= bank.full_name %>
                </td>
                <td>
                  <%= bank.bank_name %>
                </td>
                <td>
                  <%= bank.account_number %>
                </td>
                
                <td>
                  <%= bank.branch_name %>
                </td>
                <td>
                  <%= bank.ifsc %>
                </td>
                <td>
                  <%= bank.status %>
                </td>
                <td>
                  <%= bank.created_at.to_datetime.strftime("%d/%m/%Y %I:%M:%S %p") %>
                </td>
              </tr>
            <% end %>
          </thead>
        </table>
        <nav class="pagination" style="text-align:center;">
          <%= paginate @bank_details %>
        </nav>
       
     
    </div>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <br/>
    <br/>
    <br/>
  </div>
</div>

app/views/admin/index.html.erb
<%= link_to "Add New Employee", new_profile_path, :class => 'btn btn-primary' ,
 :style => "margin-top: 15px;"%>
<div class="main">
  <div class="wide_cont custom-background" style="background:transparent;">
    <div class="doc-main">
      <div class="doc-content">
        <div class="" style ="text-align: center;" ><h2>EMPLOYEE DETAILS</h2>
        <div class="rgt" style ="float:right ;" >
          <button class="btn btn-primary" style="margin-bottom: 14px;">
            Total Employees:
              <%= @profile_count %>
          </button>
          <%=  link_to("Download Employees ",download_employees_admin_index_path(format: "csv"), :class => "btn btn-primary", :style => "margin-bottom: 14px;") %>
        </div>
        
        <table class="responstable">
          <thead>
            <tr>
              <td>
                <b>
                  #
                </b>
              </td>
              <td>
                <b>
                  Employee ID
                </b>
              </td>
              <td>
                <b>
                  Employee Name
                </b>
              </td>
              <td>
                <b>
                  Joining Date
                </b>
              </td>
              <td>
                <b>
                  Mobile Number
                </b>
              </td>
              <td>
                <b>
                  Email Id
                </b>
              </td>
              <td>
                <b>
                  Gender
                </b>
              </td>

              <td>
                <b>
                  Status
                </b>
              </td>
              <td>
                <b>
                  Created At
                </b>
              </td>
              <td>
                <b>
                  Actions 
                </b>
              </td>
            </tr>
            <% @all_users.each_with_index do |user, index| %>
              <tr>
                <td>
                  <%= index %>
                </td>
                <td>
                  <%= user.employee_number %>
                </td>
                <td>
                  <%= user.name.upcase %>
                </td>
                <td>
                  <%= user.date_of_joining %>
                </td>
                <td>
                  <%= user.contact_number %>
                </td>
                <td>
                  <%= mail_to "#{user.email}" %>
                </td>
                <td>
                  <%= user.gender %>
                </td>
                <td>
                  <%= user.status %>
                </td>
                <td>
                  <%= user.created_at.to_datetime.strftime("%d/%m/%Y %I:%M:%S %p") %> 
                </td>
                <td>
                  <%= link_to "Edit", profile_edit_admin_index_path(:id=>user.id), :class => 'btn btn-primary' %>
                  </br>
                  <%= link_to "Delete",  profile_delete_admin_index_path(:id=>user.id),   data: { confirm: 'Are you sure?' },:class => 'btn btn-primary' %>
                 
                </td>
               
              </tr>
            <% end %>
          </thead>
        </table>
        <nav class="pagination" style="text-align:center;">
          <%= paginate @all_users %>
        </nav>
       
     
    </div>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <br/>
    <br/>
    <br/>
  </div>
</div>

app/views/admin/leave_application.html.erb
<div class="main">
  <div class="wide_cont custom-background" style="background:transparent;">
    <div class="doc-main">
      <div class="doc-content">
        <div class="" style ="text-align: center;" ><h2>LEAVE APPLICATIONS</h2>
        <div class="rgt" style ="float:right ;" >
        </div>
        
        <table class="responstable">
          <thead>
            <tr>
              <td>
                <b>
                  EMPLOYEE ID
                </b>
              </td>
              <td>
                <b>
                  EMPLOYEE NAME
                </b>
              </td>
              <td>
                <b>
                  LEAVE TYPE
                </b>
              </td>
              <td>
                <b>
                  START DATE
                </b>
              </td>
              <td>
                <b>
                  END DATE
                </b>
              </td>
              <td>
                <b>
                  NO OF DAYS
                </b>
              </td>
              <td>
                <b>
                  REASON
                </b>
              </td>
              <td>
                <b>
                  TOTAL N0: OF LEAVE'S TAKEN
                </b>
              </td>
              <td>
                <b>
                  CREATED AT
                </b>
              </td>
              <td>
                <b>
                  ACTIONS
                </b>
              </td>
            </tr>
            <% if @leave_details.present? %>
              <% @leave_details.each do |leave| %>
                <% profile = leave.profile %>
                <tr>
                  <td>
                    <%= profile.employee_number %>
                  </td>
                  <td>
                    <%= profile.name %>
                  </td>
                  <td>
                    <%= leave.leave_type %>
                  </td>
                  <td>
                    <%= leave.start_date %>
                  </td>
                  <td>
                    <%= leave.end_date %>
                  </td>
                  
                  <td>
                    <%= (leave.end_date.to_date - leave.start_date.to_date).to_i %>
                  </td>

                  <td>
                    <%= leave.reason %>
                  </td>
                  <td>
                    <%= profile.leave_management.count %>
                  </td>
                  
                  <td>
                    <%= leave.created_at.to_datetime.strftime("%d/%m/%Y %I:%M:%S %p") %>
                  </td>
                  <td>
                    <%= link_to "Approve", approve_leave_admin_index_path(:id=>leave.id), :class => 'btn btn-primary' %>
                    <%= link_to "Reject",  reject_leave_admin_index_path(:id=>leave.id),   data: { confirm: 'Are you sure?' },:class => 'btn btn-primary' %>
                   
                  </td>
                </tr>



              <% end %>
            <% else %>
              <b> No Details found </b>
            <% end %> 
          </thead>
        </table>
        <nav class="pagination" style="text-align:center;">
          <%= paginate @leave_details %>
        </nav>
       
     
    </div>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <br/>
    <br/>
    <br/>
  </div>
</div>

app/views/admin/profile_edit.html.erb
<%= form_for Profile.new, :url => update_profile_admin_index_path, :method => 'post' do |f| %>
  <div class="container" style ="text-align:center ;margin-top:40px;">
  <div class="" style ="text-align: center;" ><h2>EDIT EMPLOYEE </h2>  
    <div class="form-group center">
      <%= f.text_field :name, :placeholder => "Full Name", required: true, label: false,class: "form-control-new",:value=>@profile.name %>
      <%= f.hidden_field :profile_id, label: false,:value=>@profile.id %>
    </div>
    <div class="form-group center">
      <%= f.text_field :email, :placeholder => "First Name", required: true, label: false,class: "form-control-new",:value=>@profile.email %>
    </div>
    <div class="form-group center">
      <%= f.text_field :contact_number, :placeholder => "Contact Number", required: true, label: false,class: "form-control-new",:value=>@profile.contact_number %>
    </div>
    <div class="form-group center">
      <%= f.select :gender,  options_for_select(["Male","Female"]), {},:value=>@profile.gender, class: "form-control-new"%>
    </div>

    <div class="form-group center">
      <%= f.text_field :emergency_contact, :placeholder => "Emergency Number", required: true, label: false,class: "form-control-new",:value=>@profile.emergency_contact %>
    </div>
    
    
    <div class="form-group center">
      <%= f.text_field :date_of_joining, :required=>true, :id => "datepicker", class: "form-control-new", :value=>@profile.date_of_joining,:placeholder => "Date of Joining" %>
    </div> 

    <div class="form-group center">
      <%= f.text_field :date_of_birth, :required=>true,:id => "datepicker1", class: "form-control-new",:value=>@profile.date_of_birth, :placeholder => "Date of Birth"  %>
    </div>             
    
    <div class="form-group center">
      <%= f.select :job_title, options_for_select(["CSE","Developer"]), {}, :value=>@profile.job_title, class: "form-control-new" %>
    </div>
    <div class="form-group center">
      <%= f.select :reporting_manager, options_for_select(["Aathresh","Vinay"]), {}, :value=>@profile.reporting_manager, class: "form-control-new"%>
    </div>
    
    <div class="form-group center">
      <%= f.text_field :address, :placeholder => "Address", required: true, label: false,class: "form-control-new",:value=>@profile.address %>
    </div>
      
      
      <div class="clear"></div>
    </div>
  </div>  
  </div>
  
  <div class="form-group center" style ="text-align:center ;">
    <button class="btn btn-primary" type="submit">
      <% if current_page?(action: 'new') %>
        Add Employee
      <% else %>
        Update Employee
      <% end %>
    </button>
  </div>
  <div class="clear"></div>
<% end %>

<script>
$('#datepicker').datepicker({
  format: 'yyyy-mm-dd',
  todayHighlight:'TRUE',
  autoclose: true,
  });

$('#datepicker1').datepicker({
  format: 'yyyy-mm-dd',
  todayHighlight:'TRUE',
  autoclose: true,
  });
</script>