config/routes.rb
Rails.application.routes.draw do
  

  root :to => "visitors#index"
  get "signout", to: "visitors#signout"

  resources :products
  devise_for :users
  resources :attendance
  resources :messages
  resources :payslips
  resources :cab_services
  resources :administration

  resources :bank_account do
    collection do
      get 'index'
      post 'create'
      post 'new'
      get 'new'
      get 'account'
      
    end
  end

  resources :leave_management do
    collection do
      get 'index'
      post 'index'
      post 'create'
      post 'new'
      get 'new'
      get 'approve_leave'
      get 'reject_leave'
      
    end
  end

  resources :users do
    collection do
      get 'index'
      post 'create'
      post 'new'
      get 'new'
      
    end
  end

  resources :admin do
    collection do
      get 'index'
      get 'download_employees'
      get 'employee_bank_details'
      get 'account'
      get 'profile_delete'
      get 'leave_application'
      post 'profile_delete'
      get 'profile_edit'
      get 'update_profile'
      post 'update_profile'
      post 'profile_edit'
      get 'destroy'
      get 'credentials'
      get 'download_bank_accounts'
      get 'approve_leave'
      get 'reject_leave'
    
    end
  end

  resources :profile do
    collection do
      get 'index'
      post 'index'
      post 'create'
      get 'destroy'
      get 'update'
      post 'update'
      
    end
  end

  resources :administration do
    collection do
      get 'index'
      post 'index'
      post 'create'
      get 'account'
      get 'destroy'
      get 'update'
      post 'update'
    end
  end    


end  

app/models/leave_management.rb
class LeaveManagement
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::Validations

  field :profile_id, type: String
  field :user_id, type: String
  field :leave_type, type: String
  field :start_date, type: String 
  field :end_date, type: String
  field :reason, type: String
  field :reporting_manager, type: String
  field :status, type: String ,:default => "pending"
  field :employee_number, type: String
  
  belongs_to :profile
end

app/controllers/leave_management_controller.rb
class LeaveManagementController < ApplicationController
  before_filter :authenticate_user!

  def new
  	@leave_details = LeaveManagement.new
  end

  def create  
    @leave_details = LeaveManagement.new(leave_params)
    @leave_details.profile_id = current_user.profile.id
    @leave_details.save
    redirect_to leave_management_index_path, notice: 'Leave Application Sent successfully '
  end

  def index
    @profile = current_user.profile
    puts @profile.inspect
    @leave_profile = @profile.leave_management
    @leave_details = Kaminari.paginate_array(@leave_profile).page(params[:page]).per(10)
    puts 'coming to leave_details'
  end

  def approve_leave
    
  end  
  
  
  private

  def leave_params
    params.require(:leave_management).permit(:leave_type, :start_date,:end_date, :reason,:profile_id)
  end
end

app/views/leave_management/index.html.erb
<%= link_to "Apply Leave", new_leave_management_path, :class => 'btn btn-primary' ,:style => "margin-top: 15px;"%>
<div class="main">
  <div class="wide_cont custom-background" style="background:transparent;">
    <div class="doc-main">
      <div class="doc-content">
        <div class="" style ="text-align: center;" ><h2>LEAVE APPLICATIONS</h2>
        <div class="rgt" style ="float:right ;" >
          <button class="btn btn-primary">
            Total No of Leaves Taken:
              <%= @leave_details.count %>
          </button>
        </div>
        
        <table class="responstable">
          <thead>
            <tr>
              
              <td>
                <b>
                  LEAVE TYPE
                </b>
              </td>
              <td>
                <b>
                  START DATE
                </b>
              </td>
              <td>
                <b>
                  END DATE
                </b>
              </td>
              <td>
                <b>
                  NO OF DAYS
                </b>
              </td>
              <td>
                <b>
                  REASON
                </b>
              </td>
              <td>
                <b>
                  CREATED AT
                </b>
              </td>
              
            </tr>
            <% @leave_details.each do |leave| %>
              <tr>
                <td>
                  <%= leave.leave_type %>
                </td>
                <td>
                  <%= leave.start_date %>
                </td>
                <td>
                  <%= leave.end_date %>
                </td>
                
                <td>
                  <%= (leave.end_date.to_date - leave.start_date.to_date).to_i %>
                </td>

                <td>
                  <%= leave.reason %>
                </td>
                
                <td>
                  <%= leave.created_at.to_datetime.strftime("%d/%m/%Y %I:%M:%S %p") %>
                </td>
                
              </tr>
            <% end %>  
          </thead>
        </table>
        <nav class="pagination" style="text-align:center;">
          <%= paginate @leave_details %>
        </nav>
        
       
     
    </div>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <br/>
    <br/>
    <br/>
  </div>
</div>

app/views/leave_management/new.html.erb
<%= simple_form_for(LeaveManagement.new, :url => "/leave_management/create", :html => { :method => :post}) do |f| %>
  <%= f.error_notification %>
  <div class="container" style ="text-align:center ;margin-top:40px;">
  <div class="" style ="text-align: center;" ><h2>LEAVE APPLICATION</h2> 
    <div class="form-group center">
      <%= f.text_field :employee_number,:value => current_user.profile.employee_number, readonly: true, class: "form-control-new"  %>
    </div> 
    <div class="form-group center">
      <%= f.text_field :name,:value => current_user.profile.name.upcase, readonly: true, class: "form-control-new"  %>
    </div> 
    <div class="form-group center"> 
      <%= f.select :leave_type,  options_for_select(["Privilege/Sick/Casual Leave","Compensatory Off","Optional Holiday","other"]), {:prompt=>"Select Leave Type"},class: "form-control-new" %>
    </div>
    <div class="form-group center">
      <%= f.text_field :start_date, :required=>true, :id => "datepicker", class: "form-control-new",:placeholder => "From Date" %>
    </div> 

    <div class="form-group center">
      <%= f.text_field :end_date, :required=>true,:id => "datepicker1", class: "form-control-new",:placeholder => "To Date"  %>
    </div>
    <div class="form-group center">
      <%= f.text_area :reason, label: false, :input_html => { :style => "border: 1px solid #cccccc; border-radius: 4px; width: 30%; transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s; height: 34px;    padding: 6px 12px;font-size: 14px;"}, class: "form-control-new",cols: 55, rows: 5,:required=>true, :placeholder=>"Specify Reason" %>
    </div>
    
      
      
      <div class="clear"></div>
    </div>
  </div>  
  </div>
  
  <div class="form-group center" style ="text-align:center ;">
    <button class="btn btn-primary" type="submit">
      <% if current_page?(action: 'new') %>
        Apply Leave 
      <% else %>
        Cancel
      <% end %>
    </button>
  </div>
  <div class="clear"></div>
<% end %>

<script>
$('#datepicker').datepicker({
  format: 'yyyy-mm-dd',
  todayHighlight:'TRUE',
  autoclose: true,
  });

$('#datepicker1').datepicker({
  format: 'yyyy-mm-dd',
  todayHighlight:'TRUE',
  autoclose: true,
  });
</script>