config/routes.rb
Rails.application.routes.draw do
  

  root :to => "visitors#index"
  get "signout", to: "visitors#signout"

  resources :products
  devise_for :users
  resources :attendance
  resources :messages
  resources :payslips
  resources :cab_services
  resources :administration

  resources :bank_account do
    collection do
      get 'index'
      post 'create'
      post 'new'
      get 'new'
      get 'account'
      
    end
  end

  resources :leave_management do
    collection do
      get 'index'
      post 'index'
      post 'create'
      post 'new'
      get 'new'
      get 'approve_leave'
      get 'reject_leave'
      
    end
  end

  resources :users do
    collection do
      get 'index'
      post 'create'
      post 'new'
      get 'new'
      
    end
  end

  resources :admin do
    collection do
      get 'index'
      get 'download_employees'
      get 'employee_bank_details'
      get 'account'
      get 'profile_delete'
      get 'leave_application'
      post 'profile_delete'
      get 'profile_edit'
      get 'update_profile'
      post 'update_profile'
      post 'profile_edit'
      get 'destroy'
      get 'credentials'
      get 'download_bank_accounts'
      get 'approve_leave'
      get 'reject_leave'
    
    end
  end

  resources :profile do
    collection do
      get 'index'
      post 'index'
      post 'create'
      get 'destroy'
      get 'update'
      post 'update'
      
    end
  end

  resources :administration do
    collection do
      get 'index'
      post 'index'
      post 'create'
      get 'account'
      get 'destroy'
      get 'update'
      post 'update'
    end
  end    


end  

app/models/bank_account.rb
class BankAccount
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::Validations

  field :profile_id, type: String
  field :user_id, type: String
  field :full_name, type: String
  field :bank_name, type: String 
  field :account_number, type: String
  field :ifsc, type: String
  field :branch_name, type: String
  field :status, type: String ,:default => "Active"
  field :employee_number, type: String
  
  belongs_to :profile
end

app/controllers/bank_account_controller.rb
class BankAccountController < ApplicationController
  before_filter :authenticate_user!


  def new
  	@bank_details = BankAccount.new
  end

  def create  
    @bank_details = BankAccount.new(bank_params)
    @bank_details.profile_id = current_user.profile.id
    @bank_details.save
    redirect_to bank_account_index_path, notice: 'Bank Details added successfully '
  end

  def index
    @profile = current_user.profile
    puts @profile.inspect
    @bank_details = @profile.bank_account
  end
  
  
  private

  def bank_params
    params.require(:bank_account).permit(:full_name, :bank_name,:account_number,:ifsc,:branch_name,:profile_id)
  end

end

app/views/bank_account/index.html.erb
<div class="main">
  <div class="wide_cont custom-background" style="background:transparent;">
    <div class="doc-main">
      <div class="doc-content">
        <div class="" style ="text-align: center;" ><h2>BANK DETAILS</h2>
            
      <% if @bank_details.present? %>
          <table class="responstable" style ="text-align: center;width: 82%;margin-left: 12%;">
              
            <tr>
              <td>Employee ID</td>
              <td><%= @bank_details.profile.employee_number %></td>
            </tr>
            <tr>
              <td>Employee Name</td>
              <td><%= @bank_details.full_name.upcase %></td>
            </tr>
            <tr>
              <td>Bank Name</td>
              <td><%= @bank_details.bank_name.upcase %></td>
            </tr>
            <tr>
              <td>Account Number</td>
              <td><%= @bank_details.account_number %></td>
            </tr>
            <tr>
              <td>IFSC Code</td>
              <td><%= @bank_details.ifsc %></td>
            </tr>
            <tr>
              <td>Branch Name</td>
              <td><%= @bank_details.branch_name.upcase %></td>
            </tr>
            <tr>
              <td>Created At</td>
              <td><%= @bank_details.created_at.to_datetime.strftime("%d/%m/%Y %I:%M:%S %p") %></td>
            </tr>
          </table>
        
      <% else %>
        <b> No Bank Details found </b>
        </br> 
        <%= link_to "Add Bank Details", new_bank_account_path, :class => 'btn btn-primary' %>
      <% end %>  
    </div>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <br/>
    <br/>
    <br/>
  </div>
</div>

app/views/bank_account/new.html.erb
<%= simple_form_for(BankAccount.new, :url => "/bank_account/create", :html => { :method => :post}) do |f| %>
  <%= f.error_notification %>
  <div class="container" style ="text-align:center ;margin-top:40px;">
  <div class="" style ="text-align: center;" ><h2>BANK DETAILS</h2>  
    <div class="form-group center">
      <%= f.input :full_name, label: false, :input_html => { :style => "border: 1px solid #cccccc; border-radius: 4px; width: 30%; transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s; height: 34px;    padding: 6px 12px;font-size: 14px;"}, :required=>true, :placeholder=>"Full Name as per bank record" %>
    </div>
    <div class="form-group center">
      <%= f.input :bank_name, label: false, :input_html => { :style => "border: 1px solid #cccccc; border-radius: 4px; width: 30%; transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s; height: 34px;    padding: 6px 12px;font-size: 14px;"}, :required=>true, :placeholder=>"Bank Name" %>
    </div>
    <div class="form-group center">
      <%= f.input :account_number, label: false, :input_html => { :style => "border: 1px solid #cccccc; border-radius: 4px; width: 30%; transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s; height: 34px;    padding: 6px 12px;font-size: 14px;"}, :required=>true, :placeholder=>"Account Number" %>
    </div>
    <div class="form-group center">
      <%= f.input :ifsc, label: false, :input_html => { :style => "border: 1px solid #cccccc; border-radius: 4px; width: 30%; transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s; height: 34px;    padding: 6px 12px;font-size: 14px;"}, :required=>true, :placeholder=>"IFSC Code" %>
    </div>
    <div class="form-group center">
      <%= f.input :branch_name, label: false, :input_html => { :style => "border: 1px solid #cccccc; border-radius: 4px; width: 30%; transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s; height: 34px;    padding: 6px 12px;font-size: 14px;"}, :required=>true, :placeholder=>"Branch Name" %>
    </div>
      
      
      <div class="clear"></div>
    </div>
  </div>  
  </div>
  
  <div class="form-group center" style ="text-align:center ;">
    <button class="btn btn-primary" type="submit">
      <% if current_page?(action: 'new') %>
        Add Bank Details
      <% else %>
        Update
      <% end %>
    </button>
  </div>
  <div class="clear"></div>
<% end %>