config/routes.rb
Rails.application.routes.draw do
  

  root :to => "visitors#index"
  get "signout", to: "visitors#signout"

  resources :products
  devise_for :users
  resources :attendance
  resources :messages
  resources :payslips
  resources :cab_services
  resources :administration

  resources :bank_account do
    collection do
      get 'index'
      post 'create'
      post 'new'
      get 'new'
      get 'account'
      
    end
  end

  resources :leave_management do
    collection do
      get 'index'
      post 'index'
      post 'create'
      post 'new'
      get 'new'
      get 'approve_leave'
      get 'reject_leave'
      
    end
  end

  resources :users do
    collection do
      get 'index'
      post 'create'
      post 'new'
      get 'new'
      
    end
  end

  resources :admin do
    collection do
      get 'index'
      get 'download_employees'
      get 'employee_bank_details'
      get 'account'
      get 'profile_delete'
      get 'leave_application'
      post 'profile_delete'
      get 'profile_edit'
      get 'update_profile'
      post 'update_profile'
      post 'profile_edit'
      get 'destroy'
      get 'credentials'
      get 'download_bank_accounts'
      get 'approve_leave'
      get 'reject_leave'
    
    end
  end

  resources :profile do
    collection do
      get 'index'
      post 'index'
      post 'create'
      get 'destroy'
      get 'update'
      post 'update'
      
    end
  end

  resources :administration do
    collection do
      get 'index'
      post 'index'
      post 'create'
      get 'account'
      get 'destroy'
      get 'update'
      post 'update'
    end
  end    


end  

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fadeOut">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <% if !current_user.present?  %>
      <div class="header topnav">
        <%= image_tag("logopi.jpg", :size => "100x75",:alt => "paraginfotech" ,:style => "float: left; padding-top: 14px; padding-left: 13px;") %> 
        <span>OUR SPACE</span>
      </div>
    <% else %>
    <% end %>  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user.present? && current_user.email.eql?("aathresh@paraginfotech.com") %>
        <div><%= link_to 'Employee Details', admin_index_path, class: 'navbar-brand' ,:style => "margin-left: 27px; "%>
        <%= link_to 'Bank Accounts', employee_bank_details_admin_index_path, class: 'navbar-brand' %>
        <%= link_to 'Leave Applications', leave_application_admin_index_path, class: 'navbar-brand' %>
        </div>  
      <% elsif %>
        <% current_user.present? %>
          <%= link_to 'My Profile', profile_index_path, class: 'navbar-brand', :style => "margin-left: 27px; " %>
          <%= link_to 'Leave Management ', leave_management_index_path, class: 'navbar-brand' %>
          <%= link_to 'Bank Account', bank_account_index_path, class: 'navbar-brand' %>
          <%= link_to 'Administration', administration_index_path, class: 'navbar-brand' %>
      <else> 
           
      <% end %>  
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav" style="float:right;">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', "/signout" %></li>
<% else %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ParagInfotech CMS" %></title>
    <%= favicon_link_tag 'favicon1.ico' %>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "ParagInfotech CMS" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>